routes/web.php
<?php






/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index')->name('home');
Route::view('/about', 'about')->name('about');
Route::view('/contact', 'contact')->name('contact');
Route::view('/disclaimer', 'disclaimer')->name('disclaimer');
Route::view('/privacy', 'privacy')->name('privacy');
Route::get('/sitemap', function(){
    $categories = \App\Models\Category::has('posts')->get();
    return view('sitemap',compact('categories'));
})->name('sitemap');

Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');

Route::get('search', 'SearchController@search')->name('search');

Route::group(['as' => 'post.', 'prefix' => 'post'], function () {
    Route::get('/', 'PostController@index')->name('index');
    Route::get('/{slug}', 'PostController@details')->name('details');
    Route::get('/category/{slug}', 'PostController@category')->name('category');
    Route::get('/tag/{slug}', 'PostController@tag')->name('tag');
    Route::get('/author/{username}/profile', 'PostController@profile')->name('author.profile');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::post('favorite/{post}/add', 'FavoriteController@add')->name('post.favorite');
    Route::post('comment/{post}', 'CommentController@comment')->name('post.comment');
    Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
});

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');

    Route::get('pending/post', 'PostController@pending')->name('post.pending');
    Route::put('post/{id}/approve', 'PostController@approval')->name('post.approve');

    Route::get('favorite', 'FavoriteController@index')->name('favorite.index');

    Route::get('subscriber', 'SubscriberController@index')->name('subscriber.index');
    Route::delete('subscriber/{id}', 'SubscriberController@destroy')->name('subscriber.destroy');

    Route::get('comment', 'CommentController@index')->name('comment.index');
    Route::delete('comment/{comment}', 'CommentController@destroy')->name('comment.destroy');

    Route::get('author', 'AuthorController@index')->name('author.index');
    Route::delete('author/{author}', 'AuthorController@destroy')->name('author.destroy');
});

Route::group(['as' => 'author.', 'prefix' => 'author', 'namespace' => 'author', 'middleware' => ['auth', 'author']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    // Route::resource('tag', 'TagController');
    // Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');

    Route::get('favorite', 'FavoriteController@index')->name('favorite.index');

    Route::get('comment', 'CommentController@index')->name('comment.index');
    Route::delete('comment/{comment}', 'CommentController@destroy')->name('comment.destroy');
});

View::composer('layouts.frontend.partial.footer', function ($view) {
    $categories = App\Models\Category::all();
    $view->with('categories', $categories);
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

resources/views/category.blade.php
@extends('layouts.frontend.app')
@section('title','Category' )

@push('css')
<link href="{{asset('assets/frontend/css/posts/styles.css')}}" rel="stylesheet">

<link href="{{asset('assets/frontend/css/posts/responsive.css')}}" rel="stylesheet">

<style>
	.favorite_posts{
		color:blue
	}
	.slider {
		height: 400px;
		width: 100%;
		background-image: url("{!! asset('storage/category/'.$category->image) !!}");
		background-size: cover;
	}
	.slider > h1{
		background:rgba(100,100,100, 0.5);
	}
</style>
@endpush
@section('content')

<div class="slider display-table center-text">
		<h1 class="title display-table-cell"><b>{!!$category->name!!}</b></h1>
	</div><!-- slider -->

	<section class="blog-area section">
		<div class="container">

			<div class="row">

				@if ($posts->count() > 0 )
					@foreach ($posts as $post)
						<div class="col-lg-4 col-md-6">
							<div class="card h-100">
								<div class="single-post post-style-1">

									<div class="blog-image">
										<img src="{{asset('storage/post/'.$post->image)}}" 
										alt="{!!config('app.name').' '. $post->title!!}" 
										title="{!! strtolower($post->title) !!}"></div>

									<a class="avatar" href="{!! route('post.author.profile',$post->user->username) !!}">
										<img src="{{asset('storage/profile/slider/'.$post->user->image)}}" alt="Profile {!! $post->user->name!!}" 
										title="{!! strtolower($post->user->name) !!}"></a>

									<div class="blog-info">

										<h4 class="title">
											<a href="{!! route('post.details',$post->slug) !!}" 
												title="{!! strtolower($post->title) !!}"><b>{!! $post->title !!}</b></a>
										</h4>

										<ul class="post-footer">
											<li>
												@guest
												<a href="javascript:void(0)" onclick="toastr.info('To add favorite list. You need to login first.', 'Info',{
													closeButton:true,
													progressBar:true,
												})"><i class="ion-heart"></i>{!! $post->favorite_to_users->count()!!}</a>
												@else
												<a href="javascript:void(0)" 
												onclick="document.getElementById('favorite-form-{!! $post->id !!}').submit();" 
												class="{!! !auth()->user()->favorite_posts()->where('post_id',$post->id)->count() == 0 ? 'favorite_posts' :''!!} ">
													<i class="ion-heart"></i>{!! $post->favorite_to_users->count()!!}
												</a>
												
												{!! Form::open(['route'=>['post.favorite',$post->id],'id'=>'favorite-form-'.$post->id,'style'=>'display:none;'])!!}
												{!! Form::close()!!}
												@endguest
											</li>
											<li><a href="#"><i class="ion-chatbubble"></i>{!!$post->comments()->count()!!}</a>
											</li>
											<li><a href="#"><i class="ion-eye"></i>{!! $post->view!!}</a></li>
										</ul>

									</div><!-- blog-info -->
								</div><!-- single-post -->
							</div><!-- card -->
						</div><!-- col-lg-4 col-md-6 -->
					@endforeach
				@else
				<div class="col-lg-12 col-md-12">
						<div class="card h-100">
							<div class="single-post post-style-1">
								<div class="blog-info">
									<h4 class="title">
										<strong>Sorry, No post found :( </strong>
									</h4>
								</div><!-- blog-info -->
							</div><!-- single-post -->
						</div><!-- card -->
					</div><!-- col-lg-4 col-md-6 -->
				@endif

			</div><!-- row -->

			{{$posts->links()}}
			

		</div><!-- container -->
	</section><!-- section -->


@endsection

@push('swiper')

@endpush

resources/views/contact.blade.php
@extends('layouts.frontend.app')

@section('title','Contact')
    
@push('css')
<link href="{{asset('assets/frontend/css/auth/styles.css')}}" rel="stylesheet">
<link href="{{asset('assets/frontend/css/auth/responsive.css')}}" rel="stylesheet">
@endpush

@section('content')
<div class="slider display-table center-text">
    <h1 class="title display-table-cell"><b>Contact</b></h1>
</div><!-- slider -->

<section class="blog-area section">
    <div class="container">

        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="post-wrapper">
                    <h1>Contact</h1>
                    <hr>
                        <p align="justify">
                                Jika anda memiliki pertanyaan atau keluhan, anda bisa langsung berkomentar pada kolom komentar yang sudah tersedia. Ingat untuk menggunakan kata-kata yang sopan, maka pasti saya akan segan kepada anda. Saya tidak akan pernah melarang jika anda mengkeritik saya jika itu memang benar salah, kemungkinan saya akan senang karena anda telah memperdulikan tulisan yang saya publish. Sekali lagi terima kasih anda telah mengunjungi blog yang saya punyai.
                        </p>
                      
                </div><!-- post-wrapper -->
            </div><!-- col-sm-8 col-sm-offset-2 -->
        </div><!-- row -->

    </div><!-- container -->
</section><!-- section -->
@endsection

@push('js')
    
@endpush

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/post.blade.php
@extends('layouts.frontend.app')
@section('title')
{!!$post->title!!}
@endsection
@push('css')
<link href="{{asset('assets/frontend/css/single/styles.css')}}" rel="stylesheet">

<link href="{{asset('assets/frontend/css/single/responsive.css')}}" rel="stylesheet">

<style>
	.favorite_posts{
		color:blue;
	}
	.header-bg{
		height: 400px;
		width: 100%;
		background-image: url("{!! asset('storage/post/'.$post->image)!!}");
		background-size:cover;
	}
	.header-bg > h1{
		height: 100%;
		color:#fff;
		text-align: center;
		font-family:Roboto, sans-serif;
		padding: 11.5%;
		background:rgba(11, 10, 10, 0.5);
	}
</style>
@endpush
@section('content')
	<div class="header-bg">
		<h1 title="{!! strtolower($post->title) !!}">{!! ucwords($post->title) !!}</h1>
	</div>

	<section class="post-area section">
		<div class="container">

			<div class="row">

				<div class="col-lg-8 col-md-12 no-right-padding">

					<div class="main-post">

						<div class="blog-post-inner">

							<div class="post-info">

								<div class="left-area">
									<a class="avatar" href="{!! route('post.author.profile',$post->user->username) !!}"><img src="{!!asset('storage/profile/slider/'.$post->user->image)!!}" alt="Profile {!! $post->user->name!!}"></a>
								</div>

								<div class="middle-area">
									<a class="name" href="#"><b>{!!$post->user->name!!}</b></a>
									<h6 class="date">on {!! $post->created_at->diffForHumans() !!}</h6>
								</div>

							</div><!-- post-info -->

							<h3 class="title"><a href="#" title="{!! strtolower($post->title) !!}"><b>{!! $post->title!!}</b></a></h3>

							<div class="para">
								{!! html_entity_decode($post->body) !!}
							</div>


							<ul class="tags">
								@foreach ($post->tags as $tag)
									<li><a href="{!!route('post.tag',$tag->slug)!!}">{{$tag->name}}</a></li>
								@endforeach
							</ul>
						</div><!-- blog-post-inner -->

						<div class="post-icons-area">
							<ul class="post-icons">
									<li>
											@guest
											<a href="javascript:void(0)" onclick="toastr.info('To add favorite list. You need to login first.', 'Info',{
												closeButton:true,
												progressBar:true,
											})"><i class="ion-heart"></i>{!! $post->favorite_to_users->count()!!}</a>
											@else
											<a href="javascript:void(0)" 
											onclick="document.getElementById('favorite-form-{!! $post->id !!}').submit();" 
											class="{!! !auth()->user()->favorite_posts()->where('post_id',$post->id)->count() == 0 ? 'favorite_posts' :''!!} ">
												<i class="ion-heart"></i>{!! $post->favorite_to_users->count()!!}
											</a>
											
											{!! Form::open(['route'=>['post.favorite',$post->id],'id'=>'favorite-form-'.$post->id,'style'=>'display:none;'])!!}
											{!! Form::close()!!}
											@endguest
										</li>
										<li>
											<a href="#"><i class="ion-chatbubble"></i>
												{!!$post->comments()->count()!!}
											</a>
										</li>
										<li><a href="#"><i class="ion-eye"></i>{!! $post->view!!}</a></li>
							</ul>

							<ul class="icons">
								<li>SHARE : </li>
								<li><a href="https://www.facebook.com/sharer/sharer.php?u={{url('post',$post->slug)}}&t={!! asset('storage/post/'.$post->image)!!}" onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;"><i class="ion-social-facebook"></i></a></li>
								<li><a href="http://twitter.com/share?text={{$post->title}}&url={{url('post',$post->slug)}}" onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;"><i class="ion-social-twitter"></i></a></li>
								<li><a href="http://pinterest.com/pin/create/button/?url={{url('post',$post->slug)}}&media={!! asset('storage/post/'.$post->image)!!}&description={{$post->title}}" onclick="window.open(this.href, 'pinterest-share', 'width=550,height=235');return false;"><i class="ion-social-pinterest"></i></a></li>
							</ul>
						</div>

						<div class="post-footer post-info">
						<div class="left-area">
							<a class="avatar" href="#"><img src="{!!asset('storage/profile/slider/'.$post->user->image)!!}" alt="Profile {!! $post->user->name!!}"></a>
						</div>

						<div class="middle-area">
							<a class="name" href="#"><b>{!!$post->user->name!!}</b></a>
							<h6 class="date">on {!! $post->created_at->diffForHumans() !!}</h6>
						</div>
							

						</div><!-- post-info -->


					</div><!-- main-post -->
				</div><!-- col-lg-8 col-md-12 -->

				<div class="col-lg-4 col-md-12 no-left-padding">

					<div class="single-post info-area">

						<div class="sidebar-area about-area">
							<h4 class="title"><b>ABOUT AUTHOR</b></h4>
							<p>
								Author name is, {!!$post->user->name!!} 
							</p>
						</div>
						
						<div class="sidebar-area">
							<div class="list-group">
								<a href="#" class="list-group-item active">
									POPULAR POST
								</a>
								@foreach ($popular_posts as $popular)
								<a href="{!! route('post.index',$popular->slug) !!}" class="list-group-item">{!!$popular->title!!}</a>
								@endforeach
							</div>
						</div>

						<div class="sidebar-area tag-area">
							<h4 class="title"><b>POST CATEGORIES</b></h4>
							<ul>
								@foreach ($post->categories as $category)
									<li><a href="{!!route('post.category',$category->slug)!!}">{!!$category->name!!}</a></li>
								@endforeach
							</ul>
						</div>

						<div class="sidebar-area">
							<div class="list-group">
								<a href="#" class="list-group-item active">
									NEW POST
								</a>
								@foreach ($new_posts as $new)
								<a href="{!! route('post.index',$new->slug) !!}" class="list-group-item">{!!$new->title!!}</a>
								@endforeach
							</div>
						</div>

					</div><!-- info-area -->

				</div><!-- col-lg-4 col-md-12 -->

			</div><!-- row -->

		</div><!-- container -->
	</section><!-- post-area -->


	<section class="recomended-area section">
		<div class="container">
			<div class="row">
				@foreach ($randomposts as $randompost)
				
				<div class="col-lg-4 col-md-6">
						<div class="card h-100">
							<div class="single-post post-style-1">
	
								<div class="blog-image">
									<img src="{{asset('storage/post/'.$randompost->image)}}"
									 alt="{!! config('app.name') .' ' . $randompost->title !!}" 
									 title="{!! strtolower($randompost->title) !!}">
								</div>
	
								<a class="avatar" href="{!! route('post.author.profile',$randompost->user->username) !!}">
									<img src="{{asset('storage/profile/slider/'.$randompost->user->image)}}" 
									alt="Profile {!!$randompost->user->name !!}" 
									title="{!! strtolower($randompost->user->name) !!}"></a>
	
								<div class="blog-info">
	
									<h4 class="title">
										<a href="{!! route('post.details',$randompost->slug) !!}" 
												title="{!! strtolower($randompost->title) !!}"><b>{!! $randompost->title !!}</b></a>
									</h4>
	
									<ul class="post-footer">
										<li>
											@guest
											<a href="javascript:void(0)" onclick="toastr.info('To add favorite list. You need to login first.', 'Info',{
												closeButton:true,
												progressBar:true,
											})"><i class="ion-heart"></i>{!! $post->favorite_to_users->count()!!}</a>
											@else
											<a href="javascript:void(0)" 
											onclick="document.getElementById('favorite-form-{!! $randompost->id !!}').submit();" 
											class="{!! !auth()->user()->favorite_posts()->where('post_id',$randompost->id)->count() == 0 ? 'favorite_posts' :''!!} ">
												<i class="ion-heart"></i>{!! $randompost->favorite_to_users->count()!!}
											</a>
											
											{!! Form::open(['route'=>['post.favorite',$randompost->id],'id'=>'favorite-form-'.$randompost->id,'style'=>'display:none;'])!!}
											{!! Form::close()!!}
											@endguest
										</li>
										<li>
											<a href="#"><i class="ion-chatbubble"></i>{!!$randompost->comments()->count()!!}
											</a>
										</li>
										<li><a href="#"><i class="ion-eye"></i>{!! $randompost->view!!}</a></li>
									</ul>
	
								</div><!-- blog-info -->
							</div><!-- single-post -->
						</div><!-- card -->
					</div><!-- col-lg-4 col-md-6 -->
					
				@endforeach

			</div><!-- row -->

		</div><!-- container -->
	</section>

	<section class="comment-section">
		<div class="container">
			<h4><b>POST COMMENT</b></h4>
			<div class="row">

				<div class="col-lg-8 col-md-12">
					<div class="comment-form">
						@guest
							<p>
								For Post a new comment. You need to login. first. 
								<a href="{!!route('login')!!}" class="btn btn-link">Login</a>
							</p>
						@else
							<form method="post" action="{!! route('post.comment',$post->id)!!}">
								@csrf
								<div class="row">
									<div class="col-sm-12">
										<textarea name="comment" rows="2" class="text-area-messge form-control"
											placeholder="Enter your comment" aria-required="true" aria-invalid="false"></textarea >
									</div><!-- col-sm-12 -->
									<div class="col-sm-12">
										<button class="submit-btn" type="submit" id="form-submit"><b>POST COMMENT</b></button>
									</div><!-- col-sm-12 -->
	
								</div><!-- row -->
							</form>
						@endguest
					</div><!-- comment-form -->

					<h4><b>COMMENTS( {{$post->comments()->count()}})</b></h4>

					<div class="commnets-area" id="comments">
						@if ($post->comments()->count() > 0)
						@foreach ($post->comments as $comment)
							<div class="comment" id="comment-{!!$comment->id!!}">

								<div class="post-info">

									<div class="left-area">
										<a class="avatar" href="#"><img src="{!! asset('storage/profile/slider/'.$comment->user->image)!!}" alt="Profile Image"></a>
									</div>

									<div class="middle-area">
										<a class="name" href="#"><b>{!! $comment->user->name!!}</b></a>
										<h6 class="date">on {!! $comment->created_at->diffForHumans()!!}</h6>
									</div>

									<div class="right-area">
										<h5 class="reply-btn" ><a href="#"><b>REPLY</b></a></h5>
									</div>

								</div><!-- post-info -->

								<p>
									{!!$comment->comment!!}
								</p>

							</div>
							@endforeach
								
						@else
							<div class="comment">
									<p>No Coment yet. Be the first :)</p>
							</div>
						@endif
					</div><!-- commnets-area -->

				

					{{-- <a class="more-comment-btn" href="#"><b>VIEW MORE COMMENTS</a> --}}

				</div><!-- col-lg-8 col-md-12 -->

			</div><!-- row -->

		</div><!-- container -->
	</section>

@endsection

@push('swiper')

@endpush

resources/views/posts.blade.php
@extends('layouts.frontend.app')
@section('title','Posts' )

@push('css')
<link href="{{asset('assets/frontend/css/posts/styles.css')}}" rel="stylesheet">

<link href="{{asset('assets/frontend/css/posts/responsive.css')}}" rel="stylesheet">

<style>
	.favorite_posts{
		color:blue
	}
</style>
@endpush
@section('content')

<div class="slider display-table center-text">
		<h1 class="title display-table-cell"><b>ALL POSTS</b></h1>
	</div><!-- slider -->

	<section class="blog-area section">
		<div class="container">

			<div class="row">

					@foreach ($posts as $post)
					<div class="col-lg-4 col-md-6">
						<div class="card h-100">
							<div class="single-post post-style-1">
	
								<div class="blog-image">
									<img src="{{asset('storage/post/'.$post->image)}}" 
									alt="{!!config('app.name').' '. $post->title!!}" 
									title="{!! strtolower($post->title) !!}"></div>
	
								<a class="avatar" href="{!! route('post.author.profile',$post->user->username) !!}">
									<img src="{{asset('storage/profile/slider/'.$post->user->image)}}" alt="Profile {!! $post->user->name!!}" 
									title="{!! strtolower($post->user->name) !!}"></a>
	
								<div class="blog-info">
	
									<h4 class="title">
										<a href="{!! route('post.details',$post->slug) !!}" 
											title="{!! strtolower($post->title) !!}"><b>{!! $post->title !!}</b></a>
									</h4>
	
									<ul class="post-footer">
										<li>
											@guest
											<a href="javascript:void(0)" onclick="toastr.info('To add favorite list. You need to login first.', 'Info',{
												closeButton:true,
												progressBar:true,
											})"><i class="ion-heart"></i>{!! $post->favorite_to_users->count()!!}</a>
											@else
											<a href="javascript:void(0)" 
											onclick="document.getElementById('favorite-form-{!! $post->id !!}').submit();" 
											class="{!! !auth()->user()->favorite_posts()->where('post_id',$post->id)->count() == 0 ? 'favorite_posts' :''!!} ">
												<i class="ion-heart"></i>{!! $post->favorite_to_users->count()!!}
											</a>
											
											{!! Form::open(['route'=>['post.favorite',$post->id],'id'=>'favorite-form-'.$post->id,'style'=>'display:none;'])!!}
											{!! Form::close()!!}
											@endguest
										</li>
										<li><a href="#"><i class="ion-chatbubble"></i>{!!$post->comments()->count()!!}</a>
										</li>
										<li><a href="#"><i class="ion-eye"></i>{!! $post->view!!}</a></li>
									</ul>
	
								</div><!-- blog-info -->
							</div><!-- single-post -->
						</div><!-- card -->
					</div><!-- col-lg-4 col-md-6 -->
				@endforeach

			</div><!-- row -->

			{{$posts->links()}}
			

		</div><!-- container -->
	</section><!-- section -->


@endsection

@push('swiper')

@endpush

resources/views/profile.blade.php
@extends('layouts.frontend.app')
@section('title','Profile' )

@push('css')
<link href="{{asset('assets/frontend/css/profile/styles.css')}}" rel="stylesheet">

<link href="{{asset('assets/frontend/css/profile/responsive.css')}}" rel="stylesheet">

<style>
	.favorite_posts{
		color:blue
	}
</style>
@endpush
@section('content')
<div class="slider display-table center-text">
    <h1 class="title display-table-cell"><b>{!! $author->name!!}</b></h1>
</div><!-- slider -->

<section class="blog-area section">
    <div class="container">

        <div class="row">

            <div class="col-lg-8 col-md-12">
                    <div class="row">
                            @if ($posts->count()> 0)
                                @foreach ($posts as $post)
                                    <div class="col-lg-6 col-md-6 col-sm-12">
                                        <div class="card h-100">
                                            <div class="single-post post-style-1">
            
                                                <div class="blog-image">
                                                    <img src="{{asset('storage/post/'.$post->image)}}" 
                                                    alt="{!!config('app.name').' '. $post->title!!}" 
                                                    title="{!! strtolower($post->title) !!}"></div>
            
                                                <a class="avatar" href="{!! route('post.author.profile',$post->user->username) !!}">
                                                    <img src="{{asset('storage/profile/slider/'.$post->user->image)}}" alt="Profile {!! $post->user->name!!}" 
                                                    title="{!! strtolower($post->user->name) !!}"></a>
            
                                                <div class="blog-info">
            
                                                    <h4 class="title">
                                                        <a href="{!! route('post.details',$post->slug) !!}" 
                                                            title="{!! strtolower($post->title) !!}"><b>{!! $post->title !!}</b></a>
                                                    </h4>
            
                                                    <ul class="post-footer">
                                                        <li>
                                                            @guest
                                                            <a href="javascript:void(0)" onclick="toastr.info('To add favorite list. You need to login first.', 'Info',{
                                                                closeButton:true,
                                                                progressBar:true,
                                                            })"><i class="ion-heart"></i>{!! $post->favorite_to_users->count()!!}</a>
                                                            @else
                                                            <a href="javascript:void(0)" 
                                                            onclick="document.getElementById('favorite-form-{!! $post->id !!}').submit();" 
                                                            class="{!! !auth()->user()->favorite_posts()->where('post_id',$post->id)->count() == 0 ? 'favorite_posts' :''!!} ">
                                                                <i class="ion-heart"></i>{!! $post->favorite_to_users->count()!!}
                                                            </a>
                                                            
                                                            {!! Form::open(['route'=>['post.favorite',$post->id],'id'=>'favorite-form-'.$post->id,'style'=>'display:none;'])!!}
                                                            {!! Form::close()!!}
                                                            @endguest
                                                        </li>
                                                        <li><a href="#"><i class="ion-chatbubble"></i>{!!$post->comments()->count()!!}</a>
                                                        </li>
                                                        <li><a href="#"><i class="ion-eye"></i>{!! $post->view!!}</a></li>
                                                    </ul>
            
                                                </div><!-- blog-info -->
                                            </div><!-- single-post -->
                                        </div><!-- card -->
                                    </div><!-- col-lg-4 col-md-6 -->
                                @endforeach
                            @else
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                    <div class="card h-100">
                                        <div class="single-post post-style-1">
                                            <div class="blog-info">
                                                <h4 class="title">
                                                    <strong>Sorry, No post found :( </strong>
                                                </h4>
                                            </div><!-- blog-info -->
                                        </div><!-- single-post -->
                                    </div><!-- card -->
                                </div><!-- col-lg-4 col-md-6 -->
                            @endif
                                
            
                        </div><!-- row -->
            
                        {{$posts->links()}}

            </div><!-- col-lg-8 col-md-12 -->

            <div class="col-lg-4 col-md-12 ">

                <div class="single-post info-area ">

                    <div class="about-area">
                        <h4 class="title"><b>ABOUT AUTHOR</b></h4>
                        <p>{!! $author->name !!}</p><br>
                        <p>{!! $author->about !!}</p><br>
                        <strong>Author Since : {!! $author->created_at->toDateString() !!}</strong><br>
                        <strong>Total Posts : {!! $author->posts->count() !!}</strong><br>
                    </div>

                </div><!-- info-area -->

            </div><!-- col-lg-4 col-md-12 -->

        </div><!-- row -->

    </div><!-- container -->
</section><!-- section -->




@endsection

@push('swiper')

@endpush