routes/web.php
<?php






/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index')->name('home');
Route::view('/about', 'about')->name('about');
Route::view('/contact', 'contact')->name('contact');
Route::view('/disclaimer', 'disclaimer')->name('disclaimer');
Route::view('/privacy', 'privacy')->name('privacy');
Route::get('/sitemap', function(){
    $categories = \App\Models\Category::has('posts')->get();
    return view('sitemap',compact('categories'));
})->name('sitemap');

Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');

Route::get('search', 'SearchController@search')->name('search');

Route::group(['as' => 'post.', 'prefix' => 'post'], function () {
    Route::get('/', 'PostController@index')->name('index');
    Route::get('/{slug}', 'PostController@details')->name('details');
    Route::get('/category/{slug}', 'PostController@category')->name('category');
    Route::get('/tag/{slug}', 'PostController@tag')->name('tag');
    Route::get('/author/{username}/profile', 'PostController@profile')->name('author.profile');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::post('favorite/{post}/add', 'FavoriteController@add')->name('post.favorite');
    Route::post('comment/{post}', 'CommentController@comment')->name('post.comment');
    Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
});

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');

    Route::get('pending/post', 'PostController@pending')->name('post.pending');
    Route::put('post/{id}/approve', 'PostController@approval')->name('post.approve');

    Route::get('favorite', 'FavoriteController@index')->name('favorite.index');

    Route::get('subscriber', 'SubscriberController@index')->name('subscriber.index');
    Route::delete('subscriber/{id}', 'SubscriberController@destroy')->name('subscriber.destroy');

    Route::get('comment', 'CommentController@index')->name('comment.index');
    Route::delete('comment/{comment}', 'CommentController@destroy')->name('comment.destroy');

    Route::get('author', 'AuthorController@index')->name('author.index');
    Route::delete('author/{author}', 'AuthorController@destroy')->name('author.destroy');
});

Route::group(['as' => 'author.', 'prefix' => 'author', 'namespace' => 'author', 'middleware' => ['auth', 'author']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    // Route::resource('tag', 'TagController');
    // Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');

    Route::get('favorite', 'FavoriteController@index')->name('favorite.index');

    Route::get('comment', 'CommentController@index')->name('comment.index');
    Route::delete('comment/{comment}', 'CommentController@destroy')->name('comment.destroy');
});

View::composer('layouts.frontend.partial.footer', function ($view) {
    $categories = App\Models\Category::all();
    $view->with('categories', $categories);
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;

class AuthorController extends Controller
{
    public function index()
    {
        $authors = User::authors()
            ->withCount('posts')
            ->withCount('favorite_posts')
            ->withCount('comments')
            ->get();

        return view('admin.authors', compact('authors'));
    }
    public function destroy(User $author)
    {

        if ($author->role_id == 2) {
            $author->delete();

            toastr()->success('Author Successlly deleted', 'Success');
            return redirect()->back();

        } else {
            abort(403);
        }
    }
}

resources/views/admin/authors.blade.php
@extends('layouts.backend.app')
@push('css')
<!-- JQuery DataTable Css -->
<link href="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">
@endpush
@section('title','Authors')

@section('content')

    <div class="container-fluid">
        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            ALL AUTHORS 
                        <span class="badge bg-blue"> {{$authors->count()}}</span>
                        </h2>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Name</th>
                                        <th>Posts</th>
                                        <th>Comments</th>
                                        <th>Favorite Posts</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>No</th>
                                        <th>Name</th>
                                        <th>Posts</th>
                                        <th>Comments</th>
                                        <th>Favorite Posts</th>
                                        <th>Action</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @foreach ($authors as $i=> $author)
                                        <tr>
                                            <td>{{$i+1}}</td>
                                            <td>{{$author->name}}</td>
                                            <td>{{$author->posts_count}}</td>
                                            <td>{{$author->comments_count}}</td>
                                            <td>{{$author->favorite_posts_count}}</td>
                                            <td>
                                                <button type="button" 
                                                    class="btn btn-danger waves-effect"
                                                    onclick="deleteAuthor({{$author->id}})"
                                                    >
                                                    <i class="material-icons">delete</i>
                                                </button>
                                                <form id="delete-form-{{$author->id}}" 
                                                    action="{{route('admin.author.destroy',$author->id)}}" 
                                                    method="POST"
                                                    style="display:none;"
                                                    >
                                                    @csrf
                                                    @method('DELETE')
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Exportable Table -->
    </div>
    

@endsection
@push('js')
    
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>

@endpush
@push('script')
    <script src="{{asset('assets/backend/js/pages/tables/jquery-datatable.js')}}"></script>
    <script>
        function deleteAuthor(id){
            const swalWithBootstrapButtons = swal.mixin({
            confirmButtonClass: 'btn btn-success',
            cancelButtonClass: 'btn btn-danger',
            buttonsStyling: false,
            })

            swalWithBootstrapButtons({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel!',
            reverseButtons: true
            }).then((result) => {
            if (result.value) {
                event.preventDefault();
                document.getElementById('delete-form-'+id).submit();
                swalWithBootstrapButtons(
                'Deleted!',
                'Your data been deleted.',
                'success'
                )
            } else if (
                // Read more about handling dismissals
                result.dismiss === swal.DismissReason.cancel
            ) {
                swalWithBootstrapButtons(
                'Cancelled',
                'Your data is safe :)',
                'error'
                )
            }
            })
        }
    </script>
@endpush

resources/views/admin/comments.blade.php
@extends('layouts.backend.app')
@push('css')
<!-- JQuery DataTable Css -->
<link href="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">
@endpush
@section('title','Comments')

@section('content')

    <div class="container-fluid">
        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            ALL  COMMENT
                        <span class="badge bg-blue"> {{$comments->count()}}</span>
                        </h2>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th class="text-center">Comment Info</th>
                                        <th class="text-center">Post Info</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>No</th>
                                        <th class="text-center">Comment Info</th>
                                        <th class="text-center">Post Info</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @foreach ($comments as $i=> $comment)
                                        <tr>
                                            <td>{{$i+1}}</td>
                                            <td>
                                                <div class="media">
                                                    <div class="media-left">
                                                        <a href=""><img src="{!!asset('storage/profile/slider/'.$comment->user->image)!!}" alt="" class="media-object" width="64" height="64">
                                                        </a>
                                                    </div>
                                                    <div class="media-body">
                                                        {{$comment->user->name}}
                                                        <h4 class="media-heading">
                                                        <small>{{ $comment->created_at->diffForHumans()}}</small>
                                                        </h4>
                                                        <p>
                                                            {{$comment->comment}}
                                                        </p>
                                                        <a target="_blank" href="{!!route('post.details',$comment->post->slug .'#comment-'.$comment->id)!!}">Reply</a>
                                                    </div> 
                                                </div>
                                            </td>
                                            <td>
                                                <div class="media">
                                                    <div class="media-right">
                                                        <a target="_blank" href="{!!route('post.details',$comment->post->slug)!!}">
                                                            <img src="{!!asset('storage/post/slider/'.$comment->post->image)!!}" alt="" class="media-object" width="64" height="64">
                                                        </a>
                                                    </div>
                                                    <div class="media-body">
                                                        {{$comment->user->name}}
                                                        <a target="_blank" href="{!!route('post.details',$comment->post->slug)!!}">
                                                            <h4 class="media-heading">{{str_limit($comment->post->title,40)}}</h4>
                                                        </a>
                                                            <p>
                                                                by <strong>{{$comment->post->user->name}}<small>{{ $comment->post->created_at->diffForHumans()}}</small></strong>
                                                            </p>
                                                    </div> 
                                                </div>
                                            </td>
                                            <td>
                                                <button type="button" 
                                                    class="btn btn-danger waves-effect"
                                                    onclick="deleteComment({{$comment->id}})"
                                                    >
                                                    <i class="material-icons">delete</i>
                                                </button>
                                                <form id="comment-form-{{$comment->id}}" 
                                                    action="{{route('admin.comment.destroy',$comment->id)}}" 
                                                    method="POST"
                                                    style="display:none;"
                                                    >
                                                    @method('DELETE')
                                                    @csrf
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Exportable Table -->
    </div>
    

</body>

</html>

@endsection
@push('js')
    
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>

@endpush
@push('script')
    <script src="{{asset('assets/backend/js/pages/tables/jquery-datatable.js')}}"></script>
    <script>
        function deleteComment(id){
            const swalWithBootstrapButtons = swal.mixin({
            confirmButtonClass: 'btn btn-success',
            cancelButtonClass: 'btn btn-danger',
            buttonsStyling: false,
            })

            swalWithBootstrapButtons({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel!',
            reverseButtons: true
            }).then((result) => {
            if (result.value) {
                event.preventDefault();
                document.getElementById('comment-form-'+id).submit();
                swalWithBootstrapButtons(
                'Deleted!',
                'Your data been deleted.',
                'success'
                )
            } else if (
                // Read more about handling dismissals
                result.dismiss === swal.DismissReason.cancel
            ) {
                swalWithBootstrapButtons(
                'Cancelled',
                'Your data is safe :)',
                'error'
                )
            }
            })
        }
       
    </script>
@endpush

resources/views/admin/settings.blade.php
@extends('layouts.backend.app')
@push('css')

@endpush
@section('title',' Settings ')

@section('content')

    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            SETTINGS
                        </h2>
                    </div>
                    <div class="body">
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active">
                                <a href="#profile_settings" data-toggle="tab" aria-expanded="false">
                                    <i class="material-icons">face</i>UPDATE PROFILE
                                </a>
                            </li>
                            <li role="presentation" class="">
                                <a href="#settings_with_icon_title" data-toggle="tab" aria-expanded="false">
                                    <i class="material-icons">change_history</i>CHANGE PASSWORD
                                </a>
                            </li>
                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane fade in active" id="profile_settings">
                                <form class="form-horizontal" action="{!! route('admin.profile.update')!!}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')
                                    <div class="row clearfix">
                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                            <label for="name">Name : </label>
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                            <div class="form-group">
                                                <div class="form-line">
                                                    <input type="text" name="name" id="name" value="{!! auth()->user()->name !!}" class="form-control" placeholder="Enter your name">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row clearfix">
                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                            <label for="email">Email Address</label>
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                            <div class="form-group">
                                                <div class="form-line">
                                                    <input type="email" name="email" id="email" value="{!! auth()->user()->email !!}" class="form-control" placeholder="Enter your email address">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row clearfix">
                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                            <label for="image">Profil Image : </label>
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                            <div class="form-group">
                                                <div class="form-line">
                                                    <input type="file" name="image" id="image" class="form-control" placeholder="Enter your password">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row clearfix">
                                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                <label for="about">About : </label>
                                            </div>
                                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                <div class="form-group">
                                                    <div class="form-line">
                                                        <textarea name="about" id="about" cols="100%" class="form-control" rows="10">
                                                                {!! auth()->user()->about !!}
                                                        </textarea>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <div class="row clearfix">
                                        <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                            <button type="subbmit" class="btn btn-primary m-t-15 waves-effect">UPDATE</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div role="tabpanel" class="tab-pane fade" id="settings_with_icon_title">
                                    <form class="form-horizontal" action="{!! route('admin.password.update')!!}" method="POST" enctype="multipart/form-data">
                                        @csrf
                                        @method('PUT')
                                        <div class="row clearfix">
                                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                <label for="old_password">Old Password : </label>
                                            </div>
                                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                <div class="form-group">
                                                    <div class="form-line">
                                                        <input type="password" name="old_password" class="form-control" placeholder="Enter Old Password">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row clearfix">
                                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                <label for="password"> Password : </label>
                                            </div>
                                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                <div class="form-group">
                                                    <div class="form-line">
                                                        <input type="password" name="password" class="form-control" placeholder="Enter  your new Password">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row clearfix">
                                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                                <label for="password_confirmation">Confirm  Password : </label>
                                            </div>
                                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                                <div class="form-group">
                                                    <div class="form-line">
                                                        <input type="password" name="password_confirmation" class="form-control" placeholder="Enter your new  Password again">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row clearfix">
                                            <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                                <button type="subbmit" class="btn btn-primary m-t-15 waves-effect">UPDATE</button>
                                            </div>
                                        </div>
                                    </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    

@endsection
@push('js')
    

@endpush
@push('script')

@endpush