routes/web.php
<?php






/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index')->name('home');
Route::view('/about', 'about')->name('about');
Route::view('/contact', 'contact')->name('contact');
Route::view('/disclaimer', 'disclaimer')->name('disclaimer');
Route::view('/privacy', 'privacy')->name('privacy');
Route::get('/sitemap', function(){
    $categories = \App\Models\Category::has('posts')->get();
    return view('sitemap',compact('categories'));
})->name('sitemap');

Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');

Route::get('search', 'SearchController@search')->name('search');

Route::group(['as' => 'post.', 'prefix' => 'post'], function () {
    Route::get('/', 'PostController@index')->name('index');
    Route::get('/{slug}', 'PostController@details')->name('details');
    Route::get('/category/{slug}', 'PostController@category')->name('category');
    Route::get('/tag/{slug}', 'PostController@tag')->name('tag');
    Route::get('/author/{username}/profile', 'PostController@profile')->name('author.profile');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::post('favorite/{post}/add', 'FavoriteController@add')->name('post.favorite');
    Route::post('comment/{post}', 'CommentController@comment')->name('post.comment');
    Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
});

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');

    Route::get('pending/post', 'PostController@pending')->name('post.pending');
    Route::put('post/{id}/approve', 'PostController@approval')->name('post.approve');

    Route::get('favorite', 'FavoriteController@index')->name('favorite.index');

    Route::get('subscriber', 'SubscriberController@index')->name('subscriber.index');
    Route::delete('subscriber/{id}', 'SubscriberController@destroy')->name('subscriber.destroy');

    Route::get('comment', 'CommentController@index')->name('comment.index');
    Route::delete('comment/{comment}', 'CommentController@destroy')->name('comment.destroy');

    Route::get('author', 'AuthorController@index')->name('author.index');
    Route::delete('author/{author}', 'AuthorController@destroy')->name('author.destroy');
});

Route::group(['as' => 'author.', 'prefix' => 'author', 'namespace' => 'author', 'middleware' => ['auth', 'author']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    // Route::resource('tag', 'TagController');
    // Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');

    Route::get('favorite', 'FavoriteController@index')->name('favorite.index');

    Route::get('comment', 'CommentController@index')->name('comment.index');
    Route::delete('comment/{comment}', 'CommentController@destroy')->name('comment.destroy');
});

View::composer('layouts.frontend.partial.footer', function ($view) {
    $categories = App\Models\Category::all();
    $view->with('categories', $categories);
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

resources/views/layouts/frontend/partial/footer.blade.php
<footer>

		<div class="container">
			<div class="row">

				<div class="col-lg-4 col-md-6">
					<div class="footer-section">

						{{-- <a class="logo" href="#"><img src="{{asset('assets/frontend/images/logo.png')}}" alt="Logo Image"></a> --}}
						<p class="copyright">{{config('app.name')}} @ 2018. All rights reserved.</p>
						<p class="copyright">Designed by <a href="https://colorlib.com" target="_blank">Colorlib</a> and Develop By <a href="">Seven Team</a></p>
						<ul class="icons">
							<li><a href="#"><i class="ion-social-facebook-outline"></i></a></li>
							<li><a href="#"><i class="ion-social-twitter-outline"></i></a></li>
							<li><a href="#"><i class="ion-social-instagram-outline"></i></a></li>
							<li><a href="#"><i class="ion-social-vimeo-outline"></i></a></li>
							<li><a href="#"><i class="ion-social-pinterest-outline"></i></a></li>
						</ul>

					</div><!-- footer-section -->
				</div><!-- col-lg-4 col-md-6 -->

				<div class="col-lg-4 col-md-6">
						<div class="footer-section">
						<h4 class="title"><b>CATAGORIES</b></h4>
						<ul>
							@foreach ($categories as $category)
								<li><a href="{!!route('post.category', $category->slug)!!}">{!!$category->name!!}</a></li>
							@endforeach
							
						</ul>
						
					</div><!-- footer-section -->
				</div><!-- col-lg-4 col-md-6 -->

				<div class="col-lg-4 col-md-6">
					<div class="footer-section">

						<h4 class="title"><b>SUBSCRIBE</b></h4>
						<div class="input-area">
							<form action="{!! url('subscriber') !!}" method="POST">
								@csrf
								<input class="email-input" type="email" name="email" placeholder="Enter your email">
								<button class="submit-btn" type="submit"><i class="icon ion-ios-email-outline"></i></button>
							</form>
						</div>

					</div><!-- footer-section -->
				</div><!-- col-lg-4 col-md-6 -->

			</div><!-- row -->
		</div><!-- container -->
</footer>

resources/views/layouts/frontend/partial/header.blade.php
<header>
		<div class="container-fluid position-relative no-side-padding">

			<a href="{{url('/')}}" class="logo">Seven Team</a>

			<div class="menu-nav-icon" data-nav-menu="#main-menu"><i class="ion-navicon"></i></div>

			<ul class="main-menu visible-on-click" id="main-menu">
				{{-- <li><a href="{{url('/')}}">Home</a></li> --}}
				<li><a href="{!! route('post.index')!!}">Post</a></li>
				<li><a href="{!! route('about')!!}">About</a></li>
				<li><a href="{!! route('contact')!!}">Contact</a></li>
				<li><a href="{!! route('disclaimer')!!}">Disclaimer</a></li>
				<li><a href="{!! route('privacy')!!}">Privacy</a></li>
				<li><a href="{!! route('sitemap')!!}">Sitemap</a></li>
				@guest
					{{-- <li><a href="{!!route('login')!!}">Login</a></li> --}}
				@else
					<li><a href="{!! auth()->user()->role_id == 1 ? route('admin.dashboard') : route('author.dashboard')!!}">Dashboard</a></li>
				@endguest
			</ul><!-- main-menu -->

			<div class="src-area" style="width: 35%;">
				<form method="GET" action="{!! route('search')!!}">
					<button class="src-btn" type="submit"><i class="ion-ios-search-strong"></i></button>
					<input class="src-input" name="search" value="{!! isset($query) ? $query : ''!!}" type="text" placeholder="Type of search">
				</form>
			</div>

		</div><!-- conatiner -->
</header>

resources/views/layouts/frontend/partial/tinymce.blade.php
{{-- <script src="//cdn.tinymce.com/4/tinymce.min.js"></script> --}}
 <!-- TinyMCE -->
 <script src="{{asset('assets/backend/plugins/tinymce/tinymce.js')}}"></script>
 
<script>
$(function () {
    //TinyMCE
    URLBASE="{{url('/')}}";
    tinymce.init({
        selector: "textarea#tinymce",
        theme: "modern",
        height: 300,
        plugins: [
            'advlist autolink lists link image charmap print preview hr anchor pagebreak',
            'searchreplace wordcount visualblocks visualchars code fullscreen',
            'insertdatetime media nonbreaking save table contextmenu directionality',
            'emoticons template paste textcolor colorpicker textpattern imagetools'
        ],
        toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
        toolbar2: 'print preview media | forecolor backcolor emoticons',
        image_advtab: true,
        file_browser_callback : function(field_name, url, type, win) {
            var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
            var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

            var cmsURL = URLBASE + "/" + 'laravel-filemanager?field_name=' + field_name;
            
            if (type == 'image') {
            cmsURL = cmsURL + "&type=Images";
            } else {
            cmsURL = cmsURL + "&type=Files";
            }

            tinyMCE.activeEditor.windowManager.open({
            file : cmsURL,
            title : 'Filemanager',
            width : x * 0.8,
            height : y * 0.8,
            resizable : "yes",
            close_previous : "no"
            });
        }
    });
    tinymce.suffix = ".min";
    tinyMCE.baseURL = '{{asset('assets/backend/plugins/tinymce')}}';

    
});
</script>