routes/web.php
<?php






/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index')->name('home');
Route::view('/about', 'about')->name('about');
Route::view('/contact', 'contact')->name('contact');
Route::view('/disclaimer', 'disclaimer')->name('disclaimer');
Route::view('/privacy', 'privacy')->name('privacy');
Route::get('/sitemap', function(){
    $categories = \App\Models\Category::has('posts')->get();
    return view('sitemap',compact('categories'));
})->name('sitemap');

Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');

Route::get('search', 'SearchController@search')->name('search');

Route::group(['as' => 'post.', 'prefix' => 'post'], function () {
    Route::get('/', 'PostController@index')->name('index');
    Route::get('/{slug}', 'PostController@details')->name('details');
    Route::get('/category/{slug}', 'PostController@category')->name('category');
    Route::get('/tag/{slug}', 'PostController@tag')->name('tag');
    Route::get('/author/{username}/profile', 'PostController@profile')->name('author.profile');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::post('favorite/{post}/add', 'FavoriteController@add')->name('post.favorite');
    Route::post('comment/{post}', 'CommentController@comment')->name('post.comment');
    Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
});

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');

    Route::get('pending/post', 'PostController@pending')->name('post.pending');
    Route::put('post/{id}/approve', 'PostController@approval')->name('post.approve');

    Route::get('favorite', 'FavoriteController@index')->name('favorite.index');

    Route::get('subscriber', 'SubscriberController@index')->name('subscriber.index');
    Route::delete('subscriber/{id}', 'SubscriberController@destroy')->name('subscriber.destroy');

    Route::get('comment', 'CommentController@index')->name('comment.index');
    Route::delete('comment/{comment}', 'CommentController@destroy')->name('comment.destroy');

    Route::get('author', 'AuthorController@index')->name('author.index');
    Route::delete('author/{author}', 'AuthorController@destroy')->name('author.destroy');
});

Route::group(['as' => 'author.', 'prefix' => 'author', 'namespace' => 'author', 'middleware' => ['auth', 'author']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('settings', 'SettingsController@index')->name('settings');
    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');
    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    // Route::resource('tag', 'TagController');
    // Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');

    Route::get('favorite', 'FavoriteController@index')->name('favorite.index');

    Route::get('comment', 'CommentController@index')->name('comment.index');
    Route::delete('comment/{comment}', 'CommentController@destroy')->name('comment.destroy');
});

View::composer('layouts.frontend.partial.footer', function ($view) {
    $categories = App\Models\Category::all();
    $view->with('categories', $categories);
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;

class AuthorController extends Controller
{
    public function index()
    {
        $authors = User::authors()
            ->withCount('posts')
            ->withCount('favorite_posts')
            ->withCount('comments')
            ->get();

        return view('admin.authors', compact('authors'));
    }
    public function destroy(User $author)
    {

        if ($author->role_id == 2) {
            $author->delete();

            toastr()->success('Author Successlly deleted', 'Success');
            return redirect()->back();

        } else {
            abort(403);
        }
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\Category;
use App\Models\Tag;
use App\Http\Requests\Admin\PostRequest;
use Brian2694\Toastr\Facades\Toastr;
use ImageUpload;
use App\Notifications\AuthorPostApproved;
use App\Models\Subscriber;
use App\Notifications\NewPostNotify;
use Notification;

class PostController extends Controller
{
    public $image;

    public function __construct()
    {
        $this->image = new ImageUpload();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::latest()->get();
        return view('admin.post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all()->pluck('name', 'id');
        $tags = Tag::all()->pluck('name', 'id');
        return view('admin.post.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        $request['author'] = auth()->user()->id;
        $request['slug'] = str_slug($request->title);
        $request['is_approved'] = true;

        if (isset($request->status)) {
            $request['status'] = true;
        } else {
            $request['status'] = false;
        }

        $post = Post::create($request->except('image'));

        $post->categories()->attach($request->categories);
        $post->tags()->attach($request->tags);

        $this->image->add($request, $post, 'post');

        // $this->sendSubscribers($post); # send subscribers notify new post status active

        Toastr::success('Post Saved', 'Succses');

        return redirect()->route('admin.post.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('admin.post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::all()->pluck('name', 'id');
        $tags = Tag::all()->pluck('name', 'id');
        return view('admin.post.edit', compact('post', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, Post $post)
    {
        // $request['author'] = auth()->user()->id;
        $request['slug'] = str_slug($request->title);
        $request['is_approved'] = true;

        if (isset($request->status)) {
            $request['status'] = true;
        } else {
            $request['status'] = false;
        }

        $post->update($request->except('image'));

        $post->categories()->sync($request->categories);
        $post->tags()->sync($request->tags);

        $this->image->add($request, $post, 'post');


        Toastr::success('Post Updated', 'Succses');

        return redirect()->route('admin.post.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $this->image->delete('post', $post->image);
        $this->image->delete('post/slider', $post->image);

        $post->delete();

        Toastr::success('Post Deleted :) ', 'Success');

        return redirect()->route('admin.post.index');
    }

    public function pending()
    {

        $posts = Post::where('is_approved', false)->latest()->get();
        return view('admin.post.pending', compact('posts'));
    }

    public function approval($id)
    {
        $post = Post::find($id);
        if ($post->is_approved == false) {
            $post->is_approved = true;
            $post->save();

            $post->user->notify(new AuthorPostApproved($post));

            // $this->sendSubscribers($post);

            Toastr::success('Post Successfully Approved :) ', 'Success');
        } else {
            Toastr::info('This Post is alredy approved ', 'Info');

        }
        return redirect()->back();
    }

    public function sendSubscribers($post)
    {
        if ($post->status == true) {
            $subscribers = Subscriber::all();

            foreach ($subscribers as $key => $subscriber) {
                Notification::route('mail', $subscriber->email)->notify(new NewPostNotify($post));
            }
        }
    }
}

app/Http/Controllers/Author/CategoryController.php
<?php

namespace App\Http\Controllers\Author;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

app/Http/Controllers/Author/CommentController.php
<?php

namespace App\Http\Controllers\Author;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\Comment;

class CommentController extends Controller
{
    public function index()
    {
        $posts = Post::where('author', auth()->user()->id)->get();
        return view('author.comments', compact('posts'));
    }

    public function destroy(Comment $comment)
    {
        if ($comment->post->user->id == auth()->user()->id) {
            $comment->delete();
            toastr()->success('Comment successfully deleted ', 'Success');
            return redirect()->back();
        } else {
            abort(403);
        }

    }
}

app/Http/Controllers/Author/DashboardController.php
<?php

namespace App\Http\Controllers\Author;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
        $user = auth()->user();
        $posts = $user->posts();
        $popular_posts = $user->posts()
            ->withCount('comments')
            ->withCount('favorite_to_users')
            ->orderBy('view', 'desc')
            ->orderBy('favorite_to_users_count')
            ->take(5)->get();
        $total_pending_posts = $user->posts()->where('is_approved', false)->count();
        $all_views = $user->posts()->sum('view');
        return view('author.dashboard', compact('user', 'posts', 'popular_posts', 'total_pending_posts', 'all_views'));
    }
}

app/Http/Controllers/Author/FavoriteController.php
<?php

namespace App\Http\Controllers\Author;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FavoriteController extends Controller
{
    public function index()
    {
        $posts = auth()->user()->favorite_posts()->latest()->get();
        return view('author.favorite', compact('posts'));
    }
}

app/Http/Controllers/Author/SettingsController.php
<?php

namespace App\Http\Controllers\Author;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\ProfileSetingsRequest;
use App\Models\User;
use App\Helpers\ImageUpload;
use Toastr;
use App\Http\Requests\PasswordSettingsRequest;
use Illuminate\Support\Facades\Hash;

class SettingsController extends Controller
{
    public function index()
    {
        return view('author.settings');
    }
    public function updateProfile(ProfileSetingsRequest $request)
    {
        auth()->user()->update($request->except('image'));

        $request['slug'] = str_slug($request->name);

        $image = new ImageUpload();
        $image->add($request, auth()->user(), 'profile');

        Toastr::success('Profile Susscessfully Updated :)', 'Succsess');

        return redirect()->back();

    }

    public function updatePassword(PasswordSettingsRequest $request)
    {
        if (Hash::check($request->old_password, auth()->user()->password)) {
            if (!Hash::check($request->password, auth()->user()->password)) {
                auth()->user()->password = bcrypt($request->password);
                auth()->user()->save();

                Toastr::success('Password successfully changed', 'Success');
                auth()->logout();
                return redirect()->back();
            } else {
                Toastr::error('New Password cannot be the same as old password.', 'Error');
                return redirect()->back();
            }

        } else {
            Toastr::error('Current password not match .', 'Error');
            return redirect()->back();
        }
    }
}

app/Http/Controllers/Author/TagController.php
<?php

namespace App\Http\Controllers\Author;

use App\Models\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        //
    }
}

resources/views/author/post/_form.blade.php
<div class="row clearfix">
    <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    @if (isset($post))
                    EDIT POST
                    @else
                    ADD NEW POST
                    @endif
                </h2>
            </div>
            <div class="body">
                @include('author.post.form.left-form')
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>Categories and Tags</h2>
            </div>
            <div class="body">
                @include('author.post.form.right-form')
            </div>
        </div>
    </div>
</div>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>BODY</h2>
            </div>
            <div class="body"> 
                <textarea name="body" id="tinymce" cols="30" rows="10">
                    {{isset($post)?$post->body:''}}
                </textarea>
            </div>
        </div>
    </div>
</div>

resources/views/author/post/create.blade.php
@extends('layouts.backend.app')
@section('title', 'Add - Post')

@push('css')

    <!-- Sweet Alert Css -->
    <link href="{{asset('assets/backend/plugins/sweetalert/sweetalert.css')}}" rel="stylesheet" />
 
    <!-- Bootstrap Select Css -->
    <link href="{{asset('assets/backend/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />

@endpush

@section('content')

<div class="container-fluid">
   
    {!! Form::open(['route'=>'author.post.store','files'=>true]) !!}
    <!-- Advanced Validation -->
        @include('author.post._form')

    
    <!-- #END# Advanced Validation -->
    {!! Form::close()!!}     
</div>


@endsection

@push('js')
        <!-- Select Plugin Js -->
         <script src="{{asset('assets/backend/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>
        <!-- Jquery Validation Plugin Css -->
        <script src="{{asset('assets/backend/plugins/jquery-validation/jquery.validate.js')}}"></script>

        <!-- JQuery Steps Plugin Js -->
        <script src="{{asset('assets/backend/plugins/jquery-steps/jquery.steps.js')}}"></script>

        <!-- Sweet Alert Plugin Js -->
        <script src="{{asset('assets/backend/plugins/sweetalert/sweetalert.min.js')}}"></script>

        <!-- Waves Effect Plugin Js -->
        <script src="{{asset('assets/backend/plugins/node-waves/waves.js')}}"></script>
         <!-- TinyMCE -->
        <script src="{{asset('assets/backend/plugins/tinymce/tinymce.js')}}"></script>


        <script src="{{asset('assets/backend/js/pages/forms/form-validation.js')}}"></script>
@endpush

@push('script')
@include('layouts.frontend.partial.tinymce')

@endpush

resources/views/author/post/edit.blade.php
@extends('layouts.backend.app')
@section('title', 'Edit - Post')

@push('css')

    <!-- Sweet Alert Css -->
    <link href="{{asset('assets/backend/plugins/sweetalert/sweetalert.css')}}" rel="stylesheet" />
 
    <!-- Bootstrap Select Css -->
    <link href="{{asset('assets/backend/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />

@endpush

@section('content')

<div class="container-fluid">
    {!! Form::model($post,['route'=>['author.post.update',$post->id],'files'=>true]) !!}
        @method('PUT')
        @include('author.post._form')
    {!! Form::close()!!}
      
</div>


@endsection

@push('js')
        <!-- Select Plugin Js -->
         <script src="{{asset('assets/backend/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>
        <!-- Jquery Validation Plugin Css -->
        <script src="{{asset('assets/backend/plugins/jquery-validation/jquery.validate.js')}}"></script>

        <!-- JQuery Steps Plugin Js -->
        <script src="{{asset('assets/backend/plugins/jquery-steps/jquery.steps.js')}}"></script>

        <!-- Sweet Alert Plugin Js -->
        <script src="{{asset('assets/backend/plugins/sweetalert/sweetalert.min.js')}}"></script>

        <!-- Waves Effect Plugin Js -->
        <script src="{{asset('assets/backend/plugins/node-waves/waves.js')}}"></script>
         <!-- TinyMCE -->
        <script src="{{asset('assets/backend/plugins/tinymce/tinymce.js')}}"></script>


        <script src="{{asset('assets/backend/js/pages/forms/form-validation.js')}}"></script>
@endpush

@push('script')
@include('layouts.frontend.partial.tinymce')

@endpush

resources/views/author/post/index.blade.php
@extends('layouts.backend.app')
@push('css')
<!-- JQuery DataTable Css -->
<link href="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">
@endpush
@section('title','Post - Index')

@section('content')

    <div class="container-fluid">
        <div class="block-header">
            <a class="btn btn-primary waves-effect" href="{{route('author.post.create')}}">
                <i class="material-icons">add</i>
                <span>Add New Post</span>
            </a>
        </div>
        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            ALL POSTS 
                        <span class="badge bg-blue"> {{$posts->count()}}</span>
                        </h2>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Title</th>
                                        <th>Author</th>
                                        <th><i class="material-icons">visibility</i></th>
                                        <th>Is Approved</th>
                                        <th>Status</th>
                                        <th>Created At</th>
                                        {{-- <th>Updated At</th> --}}
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>No</th>
                                        <th>Title</th>
                                        <th>Author</th>
                                        <th><i class="material-icons">visibility</i></th>
                                        <th>Is Approved</th>
                                        <th>Status</th>
                                        <th>Created At</th>
                                        {{-- <th>Updated At</th> --}}
                                        <th>Action</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @foreach ($posts as $i=> $post)
                                        <tr>
                                            <td>{{$i+1}}</td>
                                            <td>{{str_limit($post->title,20)}}</td>
                                            <td>{{$post->user->name}}</td>
                                            <td>{{$post->view}}</td>
                                            <td>
                                                @if ($post->is_approved==true)
                                                    <span class="badge bg-blue">Approved</span>
                                                @else
                                                    <span class="badge bg-pink">Pending</span>
                                                @endif
                                            </td>
                                            <td>
                                                @if ($post->status==true)
                                                    <span class="badge bg-blue">Published</span>
                                                @else
                                                    <span class="badge bg-pink">Pending</span>
                                                @endif
                                            </td>
                                            <td>{{$post->created_at}}</td>
                                            {{-- <td>{{$post->updated_at}}</td> --}}
                                            <td>
                                                <a href="{{route('author.post.show',$post->id)}}" class="btn btn-info waves-effect">
                                                    <i class="material-icons">visibility</i>
                                                </a>
                                                <a href="{{route('author.post.edit',$post->id)}}" class="btn btn-warning waves-effect">
                                                    <i class="material-icons">edit</i>
                                                </a>
                                                <button type="button" 
                                                    class="btn btn-danger waves-effect"
                                                    onclick="deletePost({{$post->id}})"
                                                    >
                                                    <i class="material-icons">delete</i>
                                                </button>
                                                <form id="delete-form-{{$post->id}}" 
                                                    action="{{route('author.post.destroy',$post->id)}}" 
                                                    method="POST"
                                                    style="display:none;"
                                                    >
                                                    @csrf
                                                    @method('DELETE')
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Exportable Table -->
    </div>
    


@endsection
@push('js')
    
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>

@endpush
@push('script')
    <script src="{{asset('assets/backend/js/pages/tables/jquery-datatable.js')}}"></script>
    <script>
        function deletePost(id){
            const swalWithBootstrapButtons = swal.mixin({
            confirmButtonClass: 'btn btn-success',
            cancelButtonClass: 'btn btn-danger',
            buttonsStyling: false,
            })

            swalWithBootstrapButtons({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel!',
            reverseButtons: true
            }).then((result) => {
            if (result.value) {
                event.preventDefault();
                document.getElementById('delete-form-'+id).submit();
                swalWithBootstrapButtons(
                'Deleted!',
                'Your data been deleted.',
                'success'
                )
            } else if (
                // Read more about handling dismissals
                result.dismiss === swal.DismissReason.cancel
            ) {
                swalWithBootstrapButtons(
                'Cancelled',
                'Your data is safe :)',
                'error'
                )
            }
            })
        }
    </script>
@endpush